config/urls.py
from django.contrib import admin
from django.urls import path, include
from notes.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('tasks/', include('tasks.urls')),
    path('', home, name='home'),
]

notes/urls.py
from django.urls import path
from .import views


app_name = 'notes'


urlpatterns = [
    path('list/', views.notes_list, name='list'),
    path('create/', views.notes_create, name='create'),
    path('detail/<int:pk>/', views.notes_detail, name='detail'),
    path('update/<int:pk>/', views.notes_update, name='update'),
    path('delete/<int:pk>/', views.notes_delete, name='delete'),

]

tasks/urls.py
from django.urls import path
from .import views


app_name = 'tasks'

urlpatterns = [
    path('list/', views.tasks_list, name='list'),
    path('create/', views.tasks_create, name='create'),
    path('detail/<int:pk>/', views.tasks_detail, name='detail'),
    path('update/<int:pk>/', views.tasks_update, name='update'),
    path('delete/<int:pk>/', views.tasks_delete, name='delete'),
]

notes/models.py
from django.db import models
from django.shortcuts import reverse

class Notes(models.Model):
    note_title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)


    def get_detail_url(self):
        return reverse('notes:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('notes:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('notes:delete', args=[self.pk])

tasks/models.py
from django.db import models
from django.shortcuts import reverse


class Tasks(models.Model):
    task_title = models.CharField(max_length=100)
    due_date = models.DateTimeField()
    description = models.TextField()


    def get_detail_url(self):
        return reverse('tasks:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('tasks:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('tasks:delete',args=[self.pk])

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Notes



def home(request):
    return render(request, 'index.html')



def notes_list(request):
    notes = Notes.objects.all()
    ctx = {'notes': notes}
    return render(request, 'notes/notes-list.html', ctx)

def notes_create (request):
    if request.method == 'POST':
        note_title = request.POST.get('note_title')
        content = request.POST.get('content')
        if note_title and content:
            Notes.objects.create(
                note_title=note_title,
                content=content,
            )
            return redirect('notes:list')
    return render(request, 'notes/notes-form.html')



def notes_detail(request, pk):
    notes = get_object_or_404(Notes, pk=pk)
    ctx = {'notes': notes}
    return render(request, 'notes/detail.html', ctx)



def notes_update(request, pk):
    notes = get_object_or_404(Notes, pk=pk)
    if request.method == 'POST':
        note_title = request.POST.get('note_title')
        content = request.POST.get('content')
        if note_title and content:
            notes.note_title = note_title
            notes.content = content
            notes.save()
            return redirect(notes.get_detail_url())
    ctx = {'notes': notes}
    return render(request, 'notes/notes-form.html', ctx)



def notes_delete(request, pk):
    notes = get_object_or_404(Notes, pk=pk)
    notes.delete()
    return redirect('notes:list')

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Tasks


def tasks_list(request):
    tasks = Tasks.objects.all()
    ctx = {'tasks': tasks}
    return render(request, 'tasks/tasks-list.html', ctx)

def tasks_create(request):
    if request.method == 'POST':
        task_title = request.POST.get('task_title')
        due_date = request.POST.get('due_date')
        description = request.POST.get('description')
        if task_title and due_date and description:
            Tasks.objects.create(
                task_title=task_title,
                due_date=due_date,
                description=description
            )
            return redirect('tasks:list')
    return render(request, 'tasks/tasks-form.html')


def tasks_detail(request, pk):
    tasks = get_object_or_404(Tasks, pk=pk)
    ctx = {'tasks': tasks}
    return render(request, 'tasks/detail.html', ctx)


def tasks_update(request, pk):
    tasks = get_object_or_404(Tasks, pk=pk)
    if request.method == 'POST':
        task_title = request.POST.get('task_title')
        due_date = request.POST.get('due_date')
        description = request.POST.get('description')
        if task_title and due_date and description:
            tasks.task_title = tasks_create
            tasks.due_date = due_date
            tasks.description =description
            tasks.save()
            return redirect(tasks.get_detail_url())
    ctx = {'tasks': tasks}
    return render(request, 'tasks/tasks-form.html', ctx)



def tasks_delete(request, pk):
    tasks = get_object_or_404(Tasks, pk=pk)
    tasks.delete()
    return redirect('tasks:list')

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    <h1>Welcome to the Home Page</h1>
    <a href="{% url 'notes:list' %}"><h3>Notes List</h3></a>
    <a href="{% url 'tasks:list' %}"><h3>Tasks List</h3></a>
</body>
</html>

templates/notes/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ notes.title }}</title>
    <link rel="stylesheet" href="{% static 'css/note-detail.css' %}">
</head>
<body>
    <h1>{{ notes.note_title }}</h1>
    <p><strong>Content:</strong> {{ notes.content }}</p>
    <button><a href="{{ notes.get_update_url }}">Update</a></button>
    <button><a href="{{ notes.get_delete_url }}">Delete</a></button>
    <button><a href="{% url 'notes:list' %}">Back to list</a></button>

</body>
</html>

templates/notes/notes-form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Note</title>
    <link rel="stylesheet" href="{% static 'css/note-form.css' %}">
</head>
<body>
    <div class="container">
        <h1>Create Note</h1>
        <form method="post">
            {% csrf_token %}
            <button><a href="{% url 'notes:list' %}">Back to list</a></button>
            <label for="note_title">Note Title</label><br>
            <input type="text" id="note_title" name="note_title" placeholder="Enter note title"><br>

            <label for="content">Content</label><br>
            <textarea id="content" name="content" placeholder="Write your note here..."></textarea><br>


        {% if notes %}
            <button type="submit">Update</button>
            <button><a href="{{ notes.get_detail_url }}">Back to detail</a></button>
        {% else %}
            <button type="submit">Create Notes</button>
        {% endif %}
        </form>
    </div>
</body>
</html>

templates/notes/notes-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Notes List</title>
    <link rel="stylesheet" href="{% static 'css/note-list.css' %}">
</head>
<body>
    <h1>Notes List</h1>
    <button><a href="{% url 'notes:create' %}">Create Notes</a></button>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for notes in notes %}
        <a href="{{ notes.get_detail_url }}">
            <h3>{{ notes.note_title | upper }}</h3>
            <p>{{ notes.content}}</p>
        </a>
        <br><br>
    {% empty %}
        <h3>No notes</h3>
    {% endfor %}


</body>
</html>

templates/tasks/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ tasks.title }}</title>
    <link rel="stylesheet" href="{% static 'css/tasks-detail.css' %}">
</head>
<body>
    <h1>{{ tasks.task_title }}</h1>
    <p><strong>Due Date:</strong> {{ tasks.due_date }}</p>
    <p><strong>Description :</strong> {{ tasks.description }}</p>
    <button><a href="{{ tasks.get_update_url }}">Update</a></button>
    <button><a href="{{ tasks.get_delete_url }}">Delete</a></button>
    <button><a href="{% url 'tasks:list' %}">Back to list</a></button>

</body>
</html>

templates/tasks/tasks-form.html
<!DOCTYPE html>
{% load static %}
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Task</title>
    <link rel="stylesheet" href="{% static 'css/tasks-form.css' %}">
</head>
<body>
    <div class="container">
        <h1>Create Task</h1>
        <form method="post">
            {% csrf_token %}
            <button><a href="{% url 'tasks:list' %}">Back to list</a></button>
            <br>
            <label for="task_title">Task Title</label><br>
            <input type="text" id="task_title" name="task_title" required><br>

            <label for="due_date">Due Date</label><br>
            <input type="date" id="due_date" name="due_date" required><br>

            <label for="description">Description</label><br>
            <textarea id="description" name="description" required></textarea><br>
        {% if tasks %}
            <button type="submit">Update</button>
            <button><a href="{{ tasks.get_detail_url }}">Back to detail</a></button>
        {% else %}
            <button type="submit">Create Tasks</button>

        {% endif %}
        </form>
    </div>

</body>
</html>

templates/tasks/tasks-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks List</title>
    <link rel="stylesheet" href="{% static 'css/tasks-list.css' %}">
</head>
<body>
    <h1>Tasks List</h1>
    <button><a href="{% url 'tasks:create' %}">Create Tasks</a></button>
    <br>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for tasks in tasks %}
        <a href="{{ tasks.get_detail_url }}">
            <h3>{{ tasks.task_title }}</h3>
            <p>{{ tasks.due_date | date:"Y.m.d"}}</p>
        </a>
        <br><br>
    {% empty %}
        <h3>No tasks</h3>
    {% endfor %}

</body>
</html>